# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/can_split/can_split.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_split || ORIG_REF_NAME==can_split} -quiet] -quiet

# IP: bd/can_split/ip/can_split_can_top_split_0_0/can_split_can_top_split_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_split_can_top_split_0_0 || ORIG_REF_NAME==can_split_can_top_split_0_0} -quiet] -quiet

# IP: bd/can_split/ip/can_split_can_top_split_1_0/can_split_can_top_split_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_split_can_top_split_1_0 || ORIG_REF_NAME==can_split_can_top_split_1_0} -quiet] -quiet

# IP: bd/can_split/ip/can_split_can_transceiver_0_0/can_split_can_transceiver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_split_can_transceiver_0_0 || ORIG_REF_NAME==can_split_can_transceiver_0_0} -quiet] -quiet

# IP: bd/can_split/ip/can_split_can_transceiver_0_1/can_split_can_transceiver_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_split_can_transceiver_0_1 || ORIG_REF_NAME==can_split_can_transceiver_0_1} -quiet] -quiet

# XDC: /home/lic9/prj/MCUCANDRIVER/vivadoCanDriverTest/vivadoCanDriverTest.gen/sources_1/bd/can_split/can_split_ooc.xdc
